apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nexora-secrets-sync
  namespace: nexora
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: nexora-secrets # Creates standard k8s Secret named 'nexora-secrets'
    creationPolicy: Owner
  dataFrom:
    - extract:
        # Pulls DB_HOST, DB_USER, DB_PASSWORD, DB_NAME, JWT_SECRET, and INTERNAL_SERVICE_SECRET live from AWS!
        key: nexora/staging/db-credentials