apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexora

resources:
- ../../base
- external-secret.yaml
- gateway.yaml
- db-init-job.yaml

images:
- name: ghcr.io/nexora-platform/account-service
  newName: 800770414458.dkr.ecr.us-east-1.amazonaws.com/nexora/account-service
  newTag: 6bc57fe
- name: ghcr.io/nexora-platform/api-gateway
  newName: 800770414458.dkr.ecr.us-east-1.amazonaws.com/nexora/api-gateway
  newTag: 6bc57fe
- name: ghcr.io/nexora-platform/auth-service
  newName: 800770414458.dkr.ecr.us-east-1.amazonaws.com/nexora/auth-service
  newTag: 6bc57fe
- name: ghcr.io/nexora-platform/fraud-service
  newName: 800770414458.dkr.ecr.us-east-1.amazonaws.com/nexora/fraud-service
  newTag: 6bc57fe
- name: ghcr.io/nexora-platform/frontend-web
  newName: 800770414458.dkr.ecr.us-east-1.amazonaws.com/nexora/frontend-web
  newTag: 6bc57fe
- name: ghcr.io/nexora-platform/transaction-service
  newName: 800770414458.dkr.ecr.us-east-1.amazonaws.com/nexora/transaction-service
  newTag: 6bc57fe
